import React, { useState } from 'react';
import type { CitizenReport } from '../types/citizenReport';
import type { OfficialTrackingRecord } from '../types/officialAction';
import { generateGrievanceDraft, getOfficialTracking, verifyResolution } from '../services/reportingService';
import { 
  Building2, 
  ExternalLink, 
  Copy, 
  Check, 
  ShieldCheck, 
  Clock, 
  FileText, 
  AlertCircle, 
  CheckCircle2, 
  Layers,
  Send,
  HelpCircle
} from 'lucide-react';

interface OfficialActionLayerProps {
  report: CitizenReport;
}

export const OfficialActionLayer: React.FC<OfficialActionLayerProps> = ({ report }) => {
  const draft = generateGrievanceDraft(report);
  const [tracking, setTracking] = useState<OfficialTrackingRecord | undefined>(() => getOfficialTracking(report.id));
  const [copiedDraft, setCopiedDraft] = useState(false);

  // Ground Verification Form State
  const [isGroundFixed, setIsGroundFixed] = useState(true);
  const [groundCheckNote, setGroundCheckNote] = useState('');
  const [verificationSubmitted, setVerificationSubmitted] = useState(false);

  const handleCopyDraft = () => {
    if (navigator.clipboard) {
      navigator.clipboard.writeText(draft.structuredBodyText);
      setCopiedDraft(true);
      setTimeout(() => setCopiedDraft(false), 2500);
    }
  };

  const handleVerifySubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const updated = verifyResolution(report.id, isGroundFixed, groundCheckNote);
    if (updated) setTracking(updated);
    setVerificationSubmitted(true);
  };

  return (
    <div style={{ display: 'grid', gap: '1.5rem' }}>
      {/* TRUTHFULNESS & TRANSPARENCY NOTICE */}
      <div style={{
        background: 'var(--brand-soft)',
        border: '1px solid var(--brand-line)',
        borderRadius: 14,
        padding: '1rem 1.25rem',
        display: 'flex',
        alignItems: 'center',
        gap: '0.75rem',
        fontSize: '0.86rem',
        color: 'var(--ink)'
      }}>
        <ShieldCheck size={22} style={{ flexShrink: 0, color: 'var(--brand-ink)' }} />
        <div>
          <strong>JantaX Official Action Layer:</strong> JantaX provides structured grievance drafting and tracking integration with official government portals (CPGRAMS / State IPGRS). JantaX never pretends to submit a complaint unless connected via an authorized direct API gateway.
        </div>
      </div>

      {/* AUTHORITY MATRIX & DRAFT GENERATOR CARD */}
      <div style={{
        background: 'var(--surface)',
        borderRadius: 20,
        border: '1px solid var(--border)',
        padding: '1.5rem',
        boxShadow: '0 4px 16px rgba(15,23,42,0.04)'
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '1rem', marginBottom: '1.25rem' }}>
          <div>
            <span style={{
              background: 'var(--warn-soft)',
              border: '1px solid var(--warn-line)',
              color: 'var(--warn)',
              fontSize: '0.74rem',
              fontWeight: 800,
              padding: '0.2rem 0.65rem',
              borderRadius: '9999px',
              display: 'inline-flex',
              alignItems: 'center',
              gap: '0.25rem'
            }}>
              Draft Generated by JantaX · Official Portal Submission Required
            </span>
            <h3 style={{ fontSize: '1.3rem', fontWeight: 800, color: 'var(--ink)', margin: '0.4rem 0 0.2rem' }}>
              Designated Authority: {draft.relevantAuthorityName}
            </h3>
            <div style={{ fontSize: '0.85rem', color: 'var(--ink-3)' }}>
              Department: {draft.department} · Nodal Designation: {draft.nodalOfficerDesignation}
            </div>
          </div>

          <a
            href={draft.officialPortalUrl}
            target="_blank"
            rel="noopener noreferrer"
            style={{
              padding: '0.65rem 1.25rem',
              borderRadius: 10,
              background: 'var(--brand)',
              color: 'var(--on-solid)',
              fontWeight: 800,
              fontSize: '0.86rem',
              textDecoration: 'none',
              display: 'inline-flex',
              alignItems: 'center',
              gap: '0.4rem',
              boxShadow: '0 4px 14px rgba(249,115,22,0.3)'
            }}
          >
            Launch Official Portal <ExternalLink size={14} />
          </a>
        </div>

        {/* Structured Grievance Text Container */}
        <div style={{ background: 'var(--surface-inverse)', color: 'var(--ink-4)', borderRadius: 14, padding: '1.25rem', fontFamily: 'monospace', fontSize: '0.82rem', lineHeight: 1.5, position: 'relative' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.75rem', borderBottom: '1px solid rgba(255,255,255,0.1)', paddingBottom: '0.5rem' }}>
            <span style={{ color: 'var(--accent-ink)', fontWeight: 700 }}>STRUCTURED COMPLAINT DRAFT</span>
            <button
              onClick={handleCopyDraft}
              style={{
                background: 'rgba(255,255,255,0.15)',
                color: 'var(--on-solid)',
                border: 'none',
                borderRadius: 6,
                padding: '0.3rem 0.75rem',
                fontSize: '0.75rem',
                fontWeight: 700,
                cursor: 'pointer',
                display: 'inline-flex',
                alignItems: 'center',
                gap: '0.3rem'
              }}
            >
              {copiedDraft ? <Check size={12} /> : <Copy size={12} />}
              {copiedDraft ? 'Copied to Clipboard!' : 'Copy Draft Text'}
            </button>
          </div>
          <pre style={{ whiteSpace: 'pre-wrap', wordBreak: 'break-word', margin: 0 }}>
            {draft.structuredBodyText}
          </pre>
        </div>
      </div>

      {/* OFFICIAL SYSTEM REFERENCE TRACKING CARD */}
      <div style={{
        background: 'var(--surface)',
        borderRadius: 20,
        border: '1px solid var(--border)',
        padding: '1.5rem',
        boxShadow: '0 4px 16px rgba(15,23,42,0.04)'
      }}>
        <h3 style={{ fontSize: '1.15rem', fontWeight: 800, color: 'var(--ink)', marginTop: 0, marginBottom: '1rem' }}>
          Official Government System Reference & Tracking
        </h3>

        {!tracking ? (
          <div style={{ background: 'var(--surface-2)', padding: '1.25rem', borderRadius: 12, border: '1px solid var(--border)', textAlign: 'center' }}>
            <HelpCircle size={28} style={{ color: 'var(--ink-4)', marginBottom: '0.4rem' }} />
            <div style={{ fontSize: '0.9rem', fontWeight: 700, color: 'var(--ink)' }}>No Official Reference Number Linked Yet</div>
            <div style={{ fontSize: '0.8rem', color: 'var(--ink-3)', marginTop: '0.2rem' }}>
              Once submitted on CPGRAMS or State Jan Sunwai, link your official acknowledgment reference number here for automated status tracking.
            </div>
          </div>
        ) : (
          <div style={{ display: 'grid', gap: '1.25rem' }}>
            {/* Metadata Bar */}
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '0.85rem', background: 'var(--surface-2)', padding: '1rem', borderRadius: 12 }}>
              <div>
                <div style={{ fontSize: '0.74rem', color: 'var(--ink-3)', fontWeight: 600 }}>Official System</div>
                <div style={{ fontSize: '0.95rem', fontWeight: 800, color: 'var(--ink)' }}>{tracking.official_system}</div>
              </div>

              <div>
                <div style={{ fontSize: '0.74rem', color: 'var(--ink-3)', fontWeight: 600 }}>Reference Number</div>
                <div style={{ fontSize: '0.95rem', fontWeight: 800, color: 'var(--brand-ink)' }}>{tracking.reference_number}</div>
              </div>

              <div>
                <div style={{ fontSize: '0.74rem', color: 'var(--ink-3)', fontWeight: 600 }}>Submission Time</div>
                <div style={{ fontSize: '0.95rem', fontWeight: 800, color: 'var(--ink)' }}>{tracking.submission_time}</div>
              </div>

              <div>
                <div style={{ fontSize: '0.74rem', color: 'var(--ink-3)', fontWeight: 600 }}>Official Status</div>
                <div style={{ fontSize: '0.95rem', fontWeight: 800, color: tracking.status === 'Disposed / Resolved' ? 'var(--good)' : 'var(--warn)' }}>
                  {tracking.status}
                </div>
              </div>
            </div>

            {/* Official Responses Timeline */}
            <div>
              <h4 style={{ fontSize: '0.95rem', fontWeight: 800, color: 'var(--ink)', margin: '0 0 0.75rem' }}>
                Official Nodal Officer Responses ({tracking.responses.length})
              </h4>
              <div style={{ display: 'grid', gap: '0.75rem' }}>
                {tracking.responses.map((resp) => (
                  <div key={resp.id} style={{ background: 'var(--surface-2)', border: '1px solid var(--border)', borderRadius: 12, padding: '1rem' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '0.5rem' }}>
                      <div>
                        <div style={{ fontSize: '0.76rem', color: 'var(--brand-ink)', fontWeight: 800 }}>{resp.responseDate}</div>
                        <div style={{ fontSize: '0.9rem', fontWeight: 800, color: 'var(--ink)', marginTop: '0.1rem' }}>
                          {resp.officerName} ({resp.officerDesignation})
                        </div>
                      </div>
                      {resp.sourcePdfUrl && (
                        <a href={resp.sourcePdfUrl} target="_blank" rel="noopener noreferrer" style={{ fontSize: '0.74rem', color: 'var(--brand-ink)', fontWeight: 700, textDecoration: 'none', display: 'inline-flex', alignItems: 'center', gap: '0.2rem' }}>
                          Official Disposal PDF <ExternalLink size={11} />
                        </a>
                      )}
                    </div>
                    <div style={{ fontSize: '0.84rem', color: 'var(--ink-2)', marginTop: '0.5rem', lineHeight: 1.5 }}>
                      {resp.responseText}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* CITIZEN RESOLUTION VERIFICATION CARD */}
            <div style={{ background: 'var(--good-soft)', border: '1px solid var(--good-line)', borderRadius: 14, padding: '1.25rem' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '0.5rem', marginBottom: '0.85rem' }}>
                <span style={{ fontSize: '0.92rem', fontWeight: 800, color: 'var(--good)', display: 'inline-flex', alignItems: 'center', gap: '0.35rem' }}>
                  <CheckCircle2 size={18} /> Ground Verification: {tracking.resolutionVerification.verificationStatus}
                </span>
                <span style={{ fontSize: '0.78rem', fontWeight: 700, color: 'var(--good)' }}>
                  Verification Score: {tracking.resolutionVerification.groundCheckScore}/100
                </span>
              </div>

              <div style={{ fontSize: '0.84rem', color: 'var(--good)', marginBottom: '1rem', lineHeight: 1.5 }}>
                {tracking.resolutionVerification.citizenFeedbackNote}
              </div>

              {/* Resolution Verification Input */}
              {!verificationSubmitted ? (
                <form onSubmit={handleVerifySubmit} style={{ background: 'var(--surface)', borderRadius: 10, padding: '1rem', border: '1px solid var(--good-line)' }}>
                  <div style={{ fontSize: '0.82rem', fontWeight: 800, color: 'var(--ink)', marginBottom: '0.5rem' }}>
                    Conduct Physical Ground Check: Is this issue truly fixed on the ground?
                  </div>
                  <div style={{ display: 'flex', gap: '1rem', marginBottom: '0.75rem' }}>
                    <label style={{ fontSize: '0.82rem', fontWeight: 700, color: 'var(--good)', cursor: 'pointer' }}>
                      <input type="radio" name="groundFix" checked={isGroundFixed} onChange={() => setIsGroundFixed(true)} /> Yes, Truly Rectified
                    </label>
                    <label style={{ fontSize: '0.82rem', fontWeight: 700, color: 'var(--bad)', cursor: 'pointer' }}>
                      <input type="radio" name="groundFix" checked={!isGroundFixed} onChange={() => setIsGroundFixed(false)} /> No, Closed Only on Paper
                    </label>
                  </div>
                  <input
                    type="text"
                    placeholder="Enter ground verification observations..."
                    value={groundCheckNote}
                    onChange={(e) => setGroundCheckNote(e.target.value)}
                    style={{ width: '100%', padding: '0.55rem', borderRadius: 8, border: '1px solid var(--border-strong)', fontSize: '0.82rem', marginBottom: '0.75rem' }}
                    required
                  />
                  <button type="submit" style={{ padding: '0.45rem 1rem', borderRadius: 8, background: 'var(--good-solid)', color: 'var(--on-solid)', fontWeight: 800, fontSize: '0.8rem', border: 'none', cursor: 'pointer' }}>
                    Submit Ground Verification
                  </button>
                </form>
              ) : (
                <div style={{ fontSize: '0.8rem', color: 'var(--good)', fontWeight: 700 }}>
                  ✓ Ground check feedback recorded. Thank you for maintaining civic data accuracy.
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
