import type { LucideIcon } from 'lucide-react';
import {
  Construction,
  School,
  Building,
  IndianRupee,
  HardHat,
  Landmark,
  Hospital,
  Home,
  Wheat,
  Lightbulb,
  FileText,
  CloudFog,
  Map,
  Vote,
  TrendingDown,
} from 'lucide-react';
import type { ModuleMeta } from '../types';

/**
 * Master registry of all 14 JanCheck modules.
 * This drives the Home page grid, sidebar navigation, and URL routing.
 */
export const MODULE_REGISTRY: ModuleMeta[] = [
  {
    id: 'infra',
    nameHindi: 'सड़क-पुल हिसाब',
    nameEnglish: 'Infrastructure Tracker',
    icon: Construction,
    color: '#f59e0b',
    description: 'Track roads, bridges, highways — claim vs reality',
    descriptionHindi: 'सड़कें, पुल, राजमार्ग — दावा बनाम हकीकत',
    dataSource: 'MoSPI Flash Reports, PMGSY, NHAI',
    isLive: true,
    recordCount: 15,
  },
  {
    id: 'school',
    nameHindi: 'स्कूल ठीक करो',
    nameEnglish: 'School Scorecard',
    icon: School,
    color: '#3b82f6',
    description: 'Government school quality — UDISE+ vs parent check-ins',
    descriptionHindi: 'सरकारी स्कूल गुणवत्ता — सरकारी डेटा बनाम अभिभावक जांच',
    dataSource: 'UDISE+, ASER Reports',
    isLive: true,
    recordCount: 8,
  },
  {
    id: 'nagar',
    nameHindi: 'नगर स्कोरबोर्ड',
    nameEnglish: 'City Municipal Scorecard',
    icon: Building,
    color: '#8b5cf6',
    description: 'Municipal services — water, garbage, roads, drains',
    descriptionHindi: 'नगरपालिका सेवाएं — पानी, कचरा, सड़कें, नाले',
    dataSource: 'Swachh Survekshan, AMRUT',
    isLive: true,
    recordCount: 15,
  },
  {
    id: 'budget',
    nameHindi: 'पिन हिसाब',
    nameEnglish: 'PIN Budget Tracker',
    icon: IndianRupee,
    color: '#10b981',
    description: 'Where does your PIN code tax money go?',
    descriptionHindi: 'आपके पिन कोड का टैक्स पैसा कहां जाता है?',
    dataSource: 'Union/State Budget PDFs, Expenditure Reports',
    isLive: true,
    recordCount: 5,
  },
  {
    id: 'contractor',
    nameHindi: 'ठेकेदार लेजर',
    nameEnglish: 'Contractor Ledger',
    icon: HardHat,
    color: '#ef4444',
    description: 'Who got the contract? How much? Delivered what?',
    descriptionHindi: 'ठेका किसको मिला? कितने में? क्या दिया?',
    dataSource: 'GeM, CPPP Tender Awards',
    isLive: true,
    recordCount: 25,
  },
  {
    id: 'andhbhakt',
    nameHindi: 'अंधभक्त स्टेट',
    nameEnglish: 'State CM Accountability',
    icon: Landmark,
    color: '#dc2626',
    description: 'State Chief Ministers claims vs CAG audits & RTIs side-by-side',
    descriptionHindi: 'मुख्यमंत्रियों के दावे बनाम CAG ऑडिट और RTI हकीकत',
    dataSource: 'CAG State Reports, PIB, Twitter, RTIs',
    isLive: true,
    recordCount: 13,
  },
  {
    id: 'hospital',
    nameHindi: 'अस्पताल जांच',
    nameEnglish: 'Hospital/PHC Checker',
    icon: Hospital,
    color: '#ec4899',
    description: 'Is your PHC open? Doctor present? Medicines available?',
    descriptionHindi: 'आपका PHC खुला है? डॉक्टर है? दवाइयां हैं?',
    dataSource: 'HMIS, NHM Facility Registry',
    isLive: true,
    recordCount: 12,
  },
  {
    id: 'rera',
    nameHindi: 'RERA सच',
    nameEnglish: 'RERA Reality Check',
    icon: Home,
    color: '#06b6d4',
    description: 'Builder promise vs possession reality',
    descriptionHindi: 'बिल्डर का वादा बनाम कब्ज़ा हकीकत',
    dataSource: 'State RERA Portals',
    isLive: true,
    recordCount: 8,
  },
  {
    id: 'ration',
    nameHindi: 'राशन रिपोर्ट',
    nameEnglish: 'PDS/Ration Audit',
    icon: Wheat,
    color: '#d97706',
    description: 'Ration shop open? Full quota given? Quality OK?',
    descriptionHindi: 'राशन दुकान खुली? पूरा कोटा? गुणवत्ता?',
    dataSource: 'NFSA Portal, State ePOS',
    isLive: true,
    recordCount: 22,
  },
  {
    id: 'utility',
    nameHindi: 'पानी-बिजली मीटर',
    nameEnglish: 'Water/Power Utility',
    icon: Lightbulb,
    color: '#fbbf24',
    description: 'Power cuts, water hours, bill disputes',
    descriptionHindi: 'बिजली कटौती, पानी के घंटे, bill विवाद',
    dataSource: 'State Discom/Jal Board Portals',
    isLive: true,
    recordCount: 14,
  },
  {
    id: 'rti',
    nameHindi: 'RTI ट्रैकर',
    nameEnglish: 'RTI Response Tracker',
    icon: FileText,
    color: '#6366f1',
    description: 'Filed RTI? Track response time and quality',
    descriptionHindi: 'RTI दाखिल किया? जवाब का समय और गुणवत्ता देखें',
    dataSource: 'RTI Online Portal',
    isLive: true,
    recordCount: 10,
  },
  {
    id: 'pollution',
    nameHindi: 'प्रदूषण नक्शा',
    nameEnglish: 'Pollution Map',
    icon: CloudFog,
    color: '#64748b',
    description: 'Real-time AQI and river water quality for your area',
    descriptionHindi: 'आपके इलाके का AQI और नदी का पानी',
    dataSource: 'CPCB Real-time AQI, River BOD',
    isLive: true,
    recordCount: 16,
  },
  {
    id: 'land',
    nameHindi: 'ज़मीन रजिस्ट्री',
    nameEnglish: 'Land Registry Watch',
    icon: Map,
    color: '#a3e635',
    description: 'Land records, mutation status, encroachment alerts',
    descriptionHindi: 'ज़मीन रिकॉर्ड, म्यूटेशन, अतिक्रमण अलर्ट',
    dataSource: 'State Bhulekh/Dharitree Portals',
    isLive: true,
    recordCount: 18,
  },
  {
    id: 'election',
    nameHindi: 'चुनाव खर्चा',
    nameEnglish: 'Election Spend Audit',
    icon: Vote,
    color: '#f43f5e',
    description: 'Candidate declared vs actual election spending',
    descriptionHindi: 'उम्मीदवार का घोषित खर्चा बनाम असली',
    dataSource: 'ECI Affidavits, ADR Data',
    isLive: true,
    recordCount: 12,
  },
  {
    id: 'grievance',
    nameHindi: 'शिकायत स्कोर',
    nameEnglish: 'CPGRAMS Shame Index',
    icon: TrendingDown,
    color: '#0ea5e9',
    description: 'Worst performing ministries & states ranked by backlog & delays',
    descriptionHindi: 'शिकायत विलंब सूचकांक — केंद्रीय मंत्रालय और राज्य सरकारें',
    dataSource: 'DARPG CPGRAMS Monthly Reports',
    isLive: true,
    recordCount: 9,
  },
];
